version: "3.7"

services:

    mongo_db:
        container_name: mongo_db
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db

volumes:
    mongodb: