/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundryinaja;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kiki
 */
public class DataPesanan extends javax.swing.JFrame {

    /**
     * Creates new form DataPesanan
     */
    public DataPesanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        Nota = new javax.swing.JTextField();
        Proses = new javax.swing.JButton();
        Selesai = new javax.swing.JButton();
        mpemesanan = new javax.swing.JButton();
        mpengambilan = new javax.swing.JButton();
        mpengeluaran = new javax.swing.JButton();
        mdataPesanan = new javax.swing.JButton();
        mlaporan = new javax.swing.JButton();
        keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA PEMESANAN");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Nota");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nota", "Nama", "Jumlah", "Tipe", "Harga", "Tanggal Antar", "Tanggal Selesai", "Catatan", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        Nota.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        Proses.setText("Proses");
        Proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesActionPerformed(evt);
            }
        });

        Selesai.setText("Selesai");
        Selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelesaiActionPerformed(evt);
            }
        });

        mpemesanan.setText("Pemesanan");
        mpemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpemesananActionPerformed(evt);
            }
        });

        mpengambilan.setText("Pengambilan");
        mpengambilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpengambilanActionPerformed(evt);
            }
        });

        mpengeluaran.setText("Pengeluaran");
        mpengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpengeluaranActionPerformed(evt);
            }
        });

        mdataPesanan.setText("Data Pesanan");
        mdataPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdataPesananActionPerformed(evt);
            }
        });

        mlaporan.setText("Laporan");
        mlaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlaporanActionPerformed(evt);
            }
        });

        keluar.setText("X");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nota, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Proses)
                        .addGap(18, 18, 18)
                        .addComponent(Selesai)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(mpemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mpengambilan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mpengeluaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mdataPesanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mlaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mpemesanan)
                    .addComponent(mpengeluaran)
                    .addComponent(mdataPesanan)
                    .addComponent(mpengambilan)
                    .addComponent(keluar)
                    .addComponent(mlaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Proses)
                    .addComponent(Selesai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsesActionPerformed
        // TODO add your handling code here:
        Database db = new Database();
        db.updateStatus(Nota.getText(), "Proses");
        DataPesanan frame = new DataPesanan();
        frame.setVisible(true);
        dispose();
               
    }//GEN-LAST:event_ProsesActionPerformed

    private void SelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelesaiActionPerformed
        // TODO add your handling code here:
        Database db = new Database();
        db.updateStatus(Nota.getText(), "Selesai"); 
        DataPesanan frame = new DataPesanan();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_SelesaiActionPerformed

    private void tableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tableAncestorAdded
        // TODO add your handling code here:
        Connection conn = null;
        Statement stmt = null;
        ResultSet result = null;
        ResultSet row = null;
        
        DefaultTableModel tab = new DefaultTableModel(new String[]{"Nota", "Nama","Jumlah",
            "Tipe","Harga","Antar","Selesai","Catatan","Status"}, 0);
            
        String host = "jdbc:mysql://localhost:3306/projectPBO";
        String user = "root";
        String pass = null;
        String sql = "select*from pesanan where status != 'Selesai' and status !='Diambil'";
        try{
           
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(host,user,pass);
            stmt = conn.createStatement();
            result = stmt.executeQuery(sql);
            while(result.next()){
                String nota = result.getString("notaPesanan");
                String nama = result.getString("namaPemesan");
                String jml = result.getString("jumlah");
                String tipe = result.getString("tipePemesanan");
                String harga = result.getString("harga");
                String tglA = result.getString("tanggalAntar");
                String tglS = result.getString("tanggalSelesai");
                String ctt = result.getString("catatan");
                String status = result.getString("status");
                tab.addRow(new Object []{nota,nama,jml,tipe,harga,tglA,tglS,ctt,status});
            }
            table.setModel(tab);
        }catch(ClassNotFoundException | SQLException e){
            e.printStackTrace();
        }finally{
            try{
                result.close();
                stmt.close();
                conn.close();
            }catch(SQLException e){
                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_tableAncestorAdded

    private void mpemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpemesananActionPerformed
        // TODO add your handling code here:
        FormPemesanan form = new FormPemesanan();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_mpemesananActionPerformed

    private void mpengambilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpengambilanActionPerformed
        // TODO add your handling code here:
        Pengambilan data = new Pengambilan();
        data.setVisible(true);
        dispose();
    }//GEN-LAST:event_mpengambilanActionPerformed

    private void mpengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpengeluaranActionPerformed
        // TODO add your handling code here:
        FormPengeluaran menu = new FormPengeluaran();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_mpengeluaranActionPerformed

    private void mdataPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdataPesananActionPerformed
        // TODO add your handling code here:
        DataPesanan data = new  DataPesanan();
        data.setVisible(true);
        dispose();
    }//GEN-LAST:event_mdataPesananActionPerformed

    private void mlaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlaporanActionPerformed
        // TODO add your handling code here:
        LaporanKeuangan data = new LaporanKeuangan();
        data.setVisible(true);
        dispose();
    }//GEN-LAST:event_mlaporanActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        Nota.setText(""+table.getValueAt(row,0));
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nota;
    private javax.swing.JButton Proses;
    private javax.swing.JButton Selesai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton mdataPesanan;
    private javax.swing.JButton mlaporan;
    private javax.swing.JButton mpemesanan;
    private javax.swing.JButton mpengambilan;
    private javax.swing.JButton mpengeluaran;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
