/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundryinaja;

import java.awt.Color;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.WindowConstants;

/**
 *
 * @author kiki
 */
public class mPemesanan extends javax.swing.JFrame {

    /**
     * Creates new form mPemesanan
     */
    private String filter="";
    private String status="";
    private String urut;
    public mPemesanan() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH/2);
        this.getContentPane().setBackground(Color.white);
        this.urut = "notaPesanan";

    }
    public mPemesanan(String filter,String urut) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH/2);
        this.getContentPane().setBackground(Color.white);
        
        if(!filter.equals("Semua")){
            this.filter = filter;
        }
        switch(urut){
            case "Antar":
                this.urut = "tanggalAntar";
                break;
            case "Selesai":
                this.urut = "tanggalSelesai";
                break;
            case "Nota":
                this.urut = "notaPesanan";
                break;
            case "Nama":
                this.urut = "namaPemesan";
                break;
            default:
                this.urut = "notaPesanan";
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        Pesan = new javax.swing.JButton();
        lama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        catatan = new javax.swing.JTextArea();
        tipe = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Nota = new javax.swing.JTextField();
        Proses = new javax.swing.JButton();
        Selesai = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Ambil = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Tipe");

        jLabel4.setText("Lama");

        jLabel5.setText("Catatan");

        Pesan.setText("Pesan");
        Pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesanActionPerformed(evt);
            }
        });

        catatan.setColumns(20);
        catatan.setRows(5);
        jScrollPane1.setViewportView(catatan);

        tipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kg", "item" }));

        jLabel8.setBackground(new java.awt.Color(51, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("FORM PEMESANAN");

        jLabel1.setText("Nama");

        jLabel2.setText("Jumlah");

        jLabel7.setText("hari");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                    .addGap(46, 46, 46)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nama)
                                        .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(38, 38, 38)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lama)
                                                .addComponent(tipe, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel7))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(107, 107, 107)
                                    .addComponent(Pesan)))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel8)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(tipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(Pesan)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Nota.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        Proses.setText("Proses");
        Proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesActionPerformed(evt);
            }
        });

        Selesai.setText("Selesai");
        Selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelesaiActionPerformed(evt);
            }
        });

        jLabel6.setText("Nota");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nota", "Nama", "Jumlah", "Tipe", "Harga", "Tanggal Antar", "Tanggal Selesai", "Catatan", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        jLabel9.setBackground(new java.awt.Color(51, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("DATA PEMESANAN");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filter Status", "Semua", "Waiting", "Proses", "Selesai", "Diambil" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });

        Ambil.setText("Ambil");
        Ambil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmbilActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urutkan", "Antar", "Selesai", "Nota", "Nama", " " }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                        .addComponent(Ambil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Proses, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Nota, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Proses)
                    .addComponent(Selesai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ambil)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(Nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(62, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setBackground(new java.awt.Color(51, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("PEMESANAN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(184, 184, 184)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                    .addGap(185, 185, 185)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jLabel10)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesanActionPerformed
        // TODO add your handling code here:
        Pemesanan pesan = new Pemesanan();
        Database data = new Database();
        String fnota = data.getNota(pesan.getTanggal());
        String fnama = nama.getText();
        double fjumlah = Double.parseDouble(jumlah.getText());
        String ftipe =(String) tipe.getSelectedItem();
        int flama = Integer.parseInt(lama.getText());
        double fharga = pesan.hitungHarga(pesan.harga(ftipe, flama),fjumlah);
        String ftglAntar = pesan.getTanggal();
        String ftglSelesai = pesan.kalkulasiSelesai(ftglAntar, flama);
        String fcatatan = catatan.getText();
        
        String Nota = "-------------------------------\n"
                + "Nota Pemesanan\n"
                + "-------------------------------\n\n"
                + "Nama \t: "+fnama+"\n"
                + "Jumlah \t: "+fjumlah+" "+ftipe+"\n"
                + "Harga \t: "+fharga+"\n"
                + "Antar \t: "+ftglAntar+"\n"
                + "Selesai \t: "+ftglSelesai+"\n"
                + "Catatan \t: "+fcatatan+"\n";
        int dialogButton = JOptionPane.showConfirmDialog(null,new JTextArea(Nota),"Konfirmasi",JOptionPane.YES_NO_OPTION);
        
        if(dialogButton == JOptionPane.YES_OPTION){
            data.insertPesanan(fnota, fnama, fjumlah , ftipe,fharga, ftglAntar, ftglSelesai , fcatatan);
            mPemesanan frame = new mPemesanan("Waiting",this.urut);
            frame.setVisible(true);
            frame.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
            dispose();
        }else if(dialogButton == JOptionPane.NO_OPTION){
            
        }
        /*
        NotaPemesanan frame = new NotaPemesanan(fnota,fnama,fjumlah,ftipe,fharga,ftglAntar,ftglSelesai,fcatatan);
        frame.setVisible(true);
        dispose();*/

    }//GEN-LAST:event_PesanActionPerformed

    private void ProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsesActionPerformed
        // TODO add your handling code here:
        switch(status){
            case "Waiting":
                int dialogButton = JOptionPane.showConfirmDialog(null,"Proses pesanan "+Nota.getText()+"?","Konfirmasi",JOptionPane.YES_NO_OPTION);
                if(dialogButton == JOptionPane.YES_OPTION){
                    Database db = new Database();
                    db.updateStatus(Nota.getText(), "Proses");
                    mPemesanan frame = new mPemesanan(status,this.urut);
                    frame.setVisible(true);
                    frame.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
                    dispose();
                }else if(dialogButton == JOptionPane.NO_OPTION){
                    
                }
                
                break;
            case "Selesai":
                JOptionPane.showMessageDialog(null,"Pesanan "+Nota.getText()+" sudah selesai");
                break;
            case "Diambil":
                JOptionPane.showMessageDialog(null,"Pesanan "+Nota.getText()+" sudah diambil");
                break;
        }
        

    }//GEN-LAST:event_ProsesActionPerformed

    private void SelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelesaiActionPerformed
        // TODO add your handling code here:
        switch(status){
            case "Waiting":
                JOptionPane.showMessageDialog(null,"Proses dahulu pesanan "+Nota.getText());
                break;
            case "Proses":
                int dialogButton = JOptionPane.showConfirmDialog(null,"Apakah Pesanan "+Nota.getText()+" sudah Selesai?","Konfirmasi",JOptionPane.YES_NO_OPTION);
                if(dialogButton ==  JOptionPane.YES_OPTION){
                    Database db = new Database();
                    db.updateStatus(Nota.getText(), "Selesai");
                    mPemesanan frame = new mPemesanan(status,this.urut);
                    frame.setVisible(true);
                    frame.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
                    dispose();
                    break;
                }else if(dialogButton ==  JOptionPane.NO_OPTION){
                    
                }
                break;
            case "Diambil":
                JOptionPane.showMessageDialog(null,"Pesanan "+Nota.getText()+" sudah diambil");
                break;
        }
        
    }//GEN-LAST:event_SelesaiActionPerformed

    private void tableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tableAncestorAdded
        // TODO add your handling code here:
        Connection conn = null;
        Statement stmt = null;
        ResultSet result = null;
        ResultSet row = null;

        DefaultTableModel tab = new DefaultTableModel(new String[]{"Nota", "Nama","Jumlah",
            "Tipe","Harga","Antar","Selesai","Catatan","Status"}, 0);

        String host = "jdbc:mysql://localhost:3306/projectPBO";
        String user = "root";
        String pass = null;
        String sql = "select*from pesanan where status like '%"+filter+"%' order by "+this.urut+" desc";
        try{

        Class.forName("com.mysql.jdbc.Driver");
        conn = DriverManager.getConnection(host,user,pass);
        stmt = conn.createStatement();
        result = stmt.executeQuery(sql);
        while(result.next()){
            String nota = result.getString("notaPesanan");
            String nama = result.getString("namaPemesan");
            String jml = result.getString("jumlah");
            String tipe = result.getString("tipePemesanan");
            String harga = result.getString("harga");
            String tglA = result.getString("tanggalAntar");
            String tglS = result.getString("tanggalSelesai");
            String ctt = result.getString("catatan");
            String status = result.getString("status");
            tab.addRow(new Object []{nota,nama,jml,tipe,harga,tglA,tglS,ctt,status});
        }
        table.setModel(tab);
        }catch(ClassNotFoundException | SQLException e){
            e.printStackTrace();
        }finally{
            try{
                result.close();
                stmt.close();
                conn.close();
            }catch(SQLException e){
                e.printStackTrace();
            }
        }
        //*/
    }//GEN-LAST:event_tableAncestorAdded

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        Nota.setText(""+table.getValueAt(row,0));
        status = ""+table.getValueAt(row, 8);
    }//GEN-LAST:event_tableMouseClicked

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:z
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        //Do any operations you need to do when an item is selected.
            System.out.println(this.urut);
            mPemesanan menu = new mPemesanan(""+jComboBox1.getSelectedItem(),this.urut);
            menu.setVisible(true);
            this.dispose();
        } else if(evt.getStateChange() == java.awt.event.ItemEvent.DESELECTED){
        //Do any operations you need to do when an item is de-selected.
        }
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        //Do any operations you need to do when an item is selected.
            mPemesanan menu = new mPemesanan(this.filter,""+jComboBox2.getSelectedItem());
            menu.setVisible(true);
            this.dispose();
            
        } else if(evt.getStateChange() == java.awt.event.ItemEvent.DESELECTED){
        //Do any operations you need to do when an item is de-selected.
            
        }
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void AmbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmbilActionPerformed
        // TODO add your handling code here:
        switch(status){
            case "Waiting":
                JOptionPane.showMessageDialog(null,"Pesanan "+Nota.getText()+" belum diproses");
                break;
            case "Proses":
                JOptionPane.showMessageDialog(null,"Pesanan "+Nota.getText()+" sedang dalam proses");
                break;
            case "Selesai":
                Connection conn = null;
                Statement stmt = null;
                ResultSet result = null;
                String nota = Nota.getText();
                String nama ="";
                int jml =0;
                String tipe= "";
                double harga=0;
                String host = "jdbc:mysql://localhost:3306/projectPBO";
                String user = "root";
                String pass = null;
                String sql = "select*from pesanan where notaPesanan='"+nota+"'";
                try{

                    Class.forName("com.mysql.jdbc.Driver");
                    conn = DriverManager.getConnection(host,user,pass);
                    stmt = conn.createStatement();
                    result = stmt.executeQuery(sql);
                    while(result.next()){
                        nama = result.getString("namaPemesan");
                        jml = result.getInt("jumlah");
                        tipe = result.getString("tipePemesanan");
                        harga = result.getDouble("harga");
                    }
                }catch(ClassNotFoundException | SQLException e){
                    e.printStackTrace();
                }finally{
                    try{
                        result.close();
                        stmt.close();
                        conn.close();
                    }catch(SQLException e){
                        e.printStackTrace();
                    }
                }
                String notaPengambilan = "-------------------------------\n"
                + "Nota "+nota+"\n"
                + "-------------------------------\n\n"
                + "Nama \t: "+nama+"\n"
                + "Jumlah \t: "+jml+" "+tipe+"\n"
                + "Harga \t: "+harga+"\n";
                /*NotaPengambilan fnota = new NotaPengambilan(nota,nama,jml,(harga*jml),tipe);
                fnota.setVisible(true);
                dispose();*/
                int dialogButton = JOptionPane.showConfirmDialog(null,notaPengambilan,"Konfirmasi",JOptionPane.YES_NO_OPTION);
                if(dialogButton ==  JOptionPane.YES_OPTION){
                    Database data = new Database();
                    Pemesanan tgl = new Pemesanan();
                    String desc = "cucian "+jumlah+" "+tipe+" Atas Nama "+nama;
                    data.updateStatus(nota, "Diambil");
                    data.insertLaporan(nota, tgl.getTanggal(), desc, harga);
                    mPemesanan frame = new mPemesanan(status,this.urut);
                    frame.setVisible(true);
                    frame.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
                    dispose();
                    break;
                }else if(dialogButton ==  JOptionPane.NO_OPTION){
                    
                }
                break;
        }
        
    }//GEN-LAST:event_AmbilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mPemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ambil;
    private javax.swing.JTextField Nota;
    private javax.swing.JButton Pesan;
    private javax.swing.JButton Proses;
    private javax.swing.JButton Selesai;
    private javax.swing.JTextArea catatan;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField lama;
    private javax.swing.JTextField nama;
    private javax.swing.JTable table;
    private javax.swing.JComboBox<String> tipe;
    // End of variables declaration//GEN-END:variables
}
